config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #get 'posts/_form'
  get 'pages/panel'
  get 'pages/index'
  root to: 'pages#index'






 #Intento de pasar a la nueva pagina
    #devise_scope :user do
    #get 'sign_in', to: 'pages/panel'
  #end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= pages_panel_path %>">Bolsa</a>
        </li>
        <li class="nav-item">
        <%=link_to "salir",destroy_user_session_path, method: :delete, class:"nav-link js-scroll-trigger"  %>
        </li>
        <%else%>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Log In</a>
        </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/pages/index.html.erb
<header class="masthead text-center text-white">

  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">DeepWork</h1>
      <h2 class="masthead-subheading mb-0">Bolsa de empleo para Buzos Profesionales</h2>
      <a href="<%= user_facebook_omniauth_authorize_path %>" class="btn btn-primary btn-xl rounded-pill mt-5">Inicia con facebook</a>
    </div>
  </div>

</header>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img1.jpg'%>" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">DeepWork Bolsa de trabajo</h2>
          <p>La primera bolsa de trabajo dedicada a la gestion del personal certificado de buceo profesional. Reclutamos profesionales que quieran una mejor calidad de vida en cuanto a su situación profesional.<br>
          Respondiendo a las necesidades de las empresas que se encargan de contratar este tipo de profesoinales. Entregando soporte vital 24/7</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img2.jpg'%>" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">No te quedes sin trabajo</h2>
          <p>Nuestra misión es mantener a nuestros Buzos en contante movimiento, brindandoles un lugar de trabajo cada vez que sea necesario.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img3.jpg'%>"alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Si no eres Buzo profesional nosotros te preparamos</h2>
          <p>DeepWork no se reserva a la hora de reclutar Buzos profesionales, ni menos de generarlos. Preparate en cualquiera de nuestras escuelas afiliadas, certificate para ganar dinero bajo el agua como un profesional del buceo.</p>
        </div>
      </div>
    </div>
  </div>
</section>


<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img4.jpg'%>" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Conoce más sobre DeepWork</h2>
          <p>Registrate e inica con tu cuenta para ver las ultimas ofertas, ingresar a nuestra base de datos, y ser seleccionado para el trabajo ideal.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img5.jpg'%>"alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Se parte del sistema</h2>
          <p>Empieza a disfrutar ahora de los servicios de DeepWork y no temas en registrarte para esto. Comunicate con nosotros para orientarte y darte mayor información. Tu elijes.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Footer -->
<footer class="py-5 bg-black">
  <div class="container">
    <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2018</p>
  </div>
  <!-- /.container -->
</footer>

app/views/pages/panel.html.erb
<header class="masthead text-center text-white">

  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Conoce nuestros empleos</h1>
      <h2 class="masthead-subheading mb-0">Postula a algún empleo</h2>
    </div>
  </div>

</header>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img1.jpg'%>" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">En DeepWork puedes crear empleos</h2>
          <p>Crea empleos para que otros profesionales del rubro puedan postular y participar.</p>
          <a href="<%=new_post_path%>" class="btn btn-primary btn-xl rounded-pill mt-5">Crear empleo</a>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="<%= asset_path 'img3.jpg'%>"alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Ve los empleos que puedan interesarte</h2>
          <p>Aqui podras echar un vistazo de los empleos que otros profesionales ofertaron para ti.</p>
          <a href="<%=posts_path%>" class="btn btn-primary btn-xl rounded-pill mt-5">Ver empleos</a>
        </div>
      </div>
    </div>
  </div>
</section>